version: '3'

services:
  app:
    build: .
    container_name: ci-cd-dev
    ports:
      - '8787:8787'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cicd-db
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: pass
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cicd-db
    ports:
      - "5433:5432"