server:
  port: 8787

spring:
  application:
    name: "cicd"
  datasource:
    url: jdbc:postgresql://localhost:5433/cicd-db
    username: userdb
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
